### ISSUE TITLE
Any further description  ?

### ISSUE THREAD

**Issue by Adefx** [fbeek/maxcul2mqtt#3]
Hi ! i think you've done exactly what i was seeking . 
I have plenty of MAX ( eelv / Eq3 ) device and a Max cube flashed with CUL firmware.  

My original Cube always freeze or lag due to poor firmware dev, so i decide to get the MAX device working directly from Cul fw
But i'm running jeedom , a french domotic system who don't have any CUL implementation: Mqtt should be the solution for all.

Do you have any documentation on how to run your solution ?

Thx

**Comment by fbeek** [comment]
Hi,

Unfortunatly not, i hacked together this tool as intermediate solution some years ago and iam not using this tool anymore and switched to an zigbee based solution with Home Assistant. So it is as it is in this repo and i have no additional documentation.

Please have a look into the closed issues, there you will find some hints. You need nodejs so run this in version 16, and then simply do npm install and run it. You need to change the config file, I think this is self explaining, and you need the ids of your devices.

BUT i think this will not resolve your problem, a far as i know the cube Firmwares, these are quite stable.  Because you have written that you  have a lot devices, I think the cube is not lagging or unstable, it simply is running in the LOVF Error, because it has used up all  its transmit credits. For the 868MHZ Band there is a 1% rule that is hard coded in the cul and the cube, If you have a lot of devices it can happen that these credits run out an the device needs to wait before it can send more packets. That is a commen problem and you can find additional Infos in one of the closed issues.

Regards
